# Generated by Django 3.0.3 on 2020-02-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_orderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='easy_orderapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(max_length=150)),
                ('content', models.CharField(max_length=150)),
                ('blogcontent', models.TextField(verbose_name='')),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='shopproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Product Title', max_length=150)),
                ('description', models.TextField(default='product description')),
                ('price', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='blogview',
        ),
    ]
