# Generated by Django 3.0.3 on 2020-02-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_orderapp', '0002_auto_20200225_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='img',
            field=models.ImageField(default='true', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.CharField(default='00.00', max_length=150),
        ),
    ]
