# Generated by Django 3.0.3 on 2020-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_orderapp', '0003_auto_20200225_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpdateForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('Password1', models.CharField(max_length=120)),
                ('password2', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
